
import React, { useState } from 'react';
import { FileText, Download, Filter, BookOpen, AlertCircle } from 'lucide-react';
import { Board, Grade, Subject, UserPreferences } from '../types';

interface PreviousPapersProps {
  preferences: UserPreferences;
}

export const PreviousPapers: React.FC<PreviousPapersProps> = ({ preferences }) => {
  // Default to user preferences, but allow changing
  const [selectedBoard, setSelectedBoard] = useState<Board>(preferences.board);
  const [selectedGrade, setSelectedGrade] = useState<Grade>(preferences.grade);
  const [selectedSubject, setSelectedSubject] = useState<Subject>(Subject.MATH);
  const [downloadingId, setDownloadingId] = useState<string | null>(null);

  // Generate last 10 years
  const currentYear = new Date().getFullYear();
  const years = Array.from({ length: 10 }, (_, i) => currentYear - 1 - i);

  // Mock paper generation logic
  const getPapers = () => {
    return years.map(year => ({
      id: `${year}-${selectedBoard}-${selectedSubject}`,
      year,
      title: `${selectedSubject} ${selectedBoard} ${selectedGrade} - ${year} Paper`,
      series: ['Set A', 'Set B', 'Set C', 'X Series', 'Y Series'][year % 5],
      size: `${(Math.random() * 3 + 0.5).toFixed(1)} MB`,
      isAvailable: true
    }));
  };

  const papers = getPapers();

  const handleDownload = (paper: typeof papers[0]) => {
    setDownloadingId(paper.id);
    
    // Simulate network delay
    setTimeout(() => {
        const content = `
EduSync - Simulated Question Paper
----------------------------------------
Board   : ${selectedBoard}
Class   : ${selectedGrade}
Subject : ${selectedSubject}
Year    : ${paper.year}
Series  : ${paper.series}
----------------------------------------

[ Section A: Objective Type ]
1. (Question placeholder for ${selectedSubject}...)
2. (Question placeholder for ${selectedSubject}...)

[ Section B: Short Answer ]
3. Explain the fundamental concepts of this topic.
4. Describe the process observed in the experiment.

[ Section C: Long Answer ]
5. Discuss in detail with diagrams where necessary.

----------------------------------------
(Note: This is a demo file generated by EduSync. 
In a real application, this would be an actual PDF scanned from the board exam.)
        `;

        const blob = new Blob([content], { type: 'text/plain' });
        const url = window.URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `${paper.title.replace(/\s+/g, '_')}.txt`; 
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        window.URL.revokeObjectURL(url);
        
        setDownloadingId(null);
    }, 1500);
  };

  return (
    <div className="max-w-5xl mx-auto space-y-6 pb-10 animate-fade-in">
      {/* Header */}
      <div className="bg-gradient-to-r from-slate-800 to-slate-900 rounded-2xl p-8 text-white shadow-lg relative overflow-hidden">
         <div className="absolute top-0 right-0 p-4 opacity-10">
            <FileText size={120} />
         </div>
         <div className="relative z-10">
            <h1 className="text-3xl font-bold mb-2 flex items-center gap-3">
                <FileText className="text-indigo-400" /> Previous Year Papers
            </h1>
            <p className="text-slate-300 text-lg max-w-2xl">
                Access and download the last 10 years of board exam papers for {selectedBoard} and NCERT. 
                Essential for exam preparation.
            </p>
         </div>
      </div>

      {/* Filters */}
      <div className="bg-white p-6 rounded-xl border border-slate-200 shadow-sm space-y-4">
         <div className="flex items-center gap-2 text-slate-800 font-semibold mb-2">
             <Filter size={18} className="text-indigo-600" />
             <h3>Filter Papers</h3>
         </div>
         <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            {/* Board Select */}
            <div className="relative">
                <label className="block text-xs font-medium text-slate-500 mb-1 uppercase tracking-wider">Board</label>
                <select 
                    value={selectedBoard}
                    onChange={(e) => setSelectedBoard(e.target.value as Board)}
                    className="w-full p-3 bg-slate-50 border border-slate-200 rounded-lg text-sm font-medium outline-none focus:ring-2 focus:ring-indigo-500 appearance-none"
                >
                    {Object.values(Board).map(b => <option key={b} value={b}>{b} Board</option>)}
                </select>
                <div className="absolute right-3 top-[2.1rem] pointer-events-none text-slate-400">
                    <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M6 9l6 6 6-6"/></svg>
                </div>
            </div>

            {/* Grade Select */}
            <div className="relative">
                <label className="block text-xs font-medium text-slate-500 mb-1 uppercase tracking-wider">Class</label>
                <select 
                    value={selectedGrade}
                    onChange={(e) => setSelectedGrade(e.target.value as Grade)}
                    className="w-full p-3 bg-slate-50 border border-slate-200 rounded-lg text-sm font-medium outline-none focus:ring-2 focus:ring-indigo-500 appearance-none"
                >
                    {Object.values(Grade).map(g => <option key={g} value={g}>{g}</option>)}
                </select>
                <div className="absolute right-3 top-[2.1rem] pointer-events-none text-slate-400">
                    <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M6 9l6 6 6-6"/></svg>
                </div>
            </div>

             {/* Subject Select */}
             <div className="relative">
                <label className="block text-xs font-medium text-slate-500 mb-1 uppercase tracking-wider">Subject</label>
                <select 
                    value={selectedSubject}
                    onChange={(e) => setSelectedSubject(e.target.value as Subject)}
                    className="w-full p-3 bg-slate-50 border border-slate-200 rounded-lg text-sm font-medium outline-none focus:ring-2 focus:ring-indigo-500 appearance-none"
                >
                    {Object.values(Subject).map(s => <option key={s} value={s}>{s}</option>)}
                </select>
                <div className="absolute right-3 top-[2.1rem] pointer-events-none text-slate-400">
                    <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M6 9l6 6 6-6"/></svg>
                </div>
            </div>
         </div>
      </div>

      {/* List */}
      <div className="space-y-4">
          <h3 className="font-semibold text-slate-700 ml-1 flex justify-between items-center">
              <span>Showing papers for {selectedBoard} - {selectedGrade} ({selectedSubject})</span>
              <span className="text-xs font-normal text-slate-500 bg-slate-100 px-2 py-1 rounded-full">10 papers found</span>
          </h3>
          
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            {papers.map((paper) => (
                <div 
                    key={paper.id} 
                    className="bg-white p-4 rounded-xl border border-slate-200 shadow-sm hover:shadow-md hover:border-indigo-200 transition-all flex items-center justify-between group cursor-pointer" 
                    onClick={() => handleDownload(paper)}
                >
                    <div className="flex items-center gap-4">
                        <div className={`w-12 h-12 rounded-lg flex items-center justify-center transition-colors relative
                            ${selectedBoard === Board.JKBOSE ? 'bg-blue-50 text-blue-600 group-hover:bg-blue-100' : 'bg-green-50 text-green-600 group-hover:bg-green-100'}`}>
                            <FileText size={24} />
                            {downloadingId === paper.id && (
                                <div className="absolute inset-0 bg-white/80 rounded-lg flex items-center justify-center">
                                    <div className="w-5 h-5 border-2 border-indigo-600 border-t-transparent rounded-full animate-spin"></div>
                                </div>
                            )}
                        </div>
                        <div>
                            <h3 className="font-semibold text-slate-800">{paper.year} Question Paper</h3>
                            <div className="flex items-center gap-3 text-xs text-slate-500 mt-1">
                                <span className="flex items-center"><BookOpen size={12} className="mr-1"/> {paper.series}</span>
                                <span>•</span>
                                <span className="flex items-center"><Download size={12} className="mr-1"/> {paper.size}</span>
                            </div>
                        </div>
                    </div>
                    <button 
                        disabled={downloadingId === paper.id}
                        className={`p-2 rounded-full transition-colors ${
                            downloadingId === paper.id 
                            ? 'text-indigo-400 bg-indigo-50' 
                            : 'text-slate-400 hover:text-indigo-600 hover:bg-indigo-50'
                        }`}
                        title="Download Paper"
                    >
                        <Download size={20} />
                    </button>
                </div>
            ))}
          </div>
      </div>

      <div className="bg-indigo-50 border border-indigo-100 rounded-lg p-4 flex items-start gap-3 text-sm text-indigo-700">
        <AlertCircle size={20} className="flex-shrink-0 mt-0.5" />
        <p>
            <strong>Note:</strong> These are simulated entries for demonstration. 
            Clicking download will generate a sample text file representing the question paper structure.
        </p>
      </div>
    </div>
  );
};
